### ISSUE TITLE
[tracing] invisible error logs if something fails setting up Tracing

### ISSUE THREAD

**Issue by PietroPasotti** [canonical/operator#1834]
I suspect something goes wrong when something errors in setting up Tracing, probably because the juju debug-log gets patched and never flushed if the charm throws an exception.

Repro:

```yaml
# charmcraft.yaml
[...]
requires:
  tracing:
    interface: tracing
  certificates:
    interface: tls-certificates   ## <<< this is the bug. Should be 'certificate-transfer'
```

```python
from ops.charm import CharmBase
from ops_tracing import Tracing

class MyCharm(CharmBase):
    def __init__(self, *args):
        super().__init__(*args)
        self.tracing = Tracing(
            self,
            tracing_relation_name='tracing',
            ca_relation_name='certificates', 
        )
```

When deploying this charm, the status clearly shows that every hook is failing and the charm is in error, **but nothing shows up in the debug-log**.

Using juju debug-hooks, I can manually run dispatch and see a stack trace:
![Image](https://github.com/user-attachments/assets/754f887e-d336-47b4-b9f8-ecde3748cf43)

This makes this kind of issues very hard to debug.
To be verified: does this apply to all exceptions thrown from `__init__`?
