### ISSUE TITLE
Document valid schema for pod's set_spec function and how to set environment variables

### ISSUE THREAD

**Issue by alexellis** [canonical/operator#463]
I am trying without any success to add an environment variable to a charm I'm building for OpenFaaS:

"env" (as per the Kubernetes schema) fails

"envConfig" as seen in the Istio example also fails.

https://github.com/juju-solutions/bundle-istio/blob/master/charms/istio-ingressgateway/reactive/charm.py#L130

```
ops.model.ModelError: b'ERROR json: unknown field "env"\n'
ops.model.ModelError: b'ERROR json: unknown field "envConfig"\n'
ops.model.ModelError: b'ERROR json: unknown field "envs"\n'
```

Attempted Charm:

```python
    def _on_config_changed(self, _=None):
        pod_spec = self._build_pod_spec()
        self.model.pod.set_spec(pod_spec)
        self.unit.status = ActiveStatus("OpenFaaS pod ready.")

    def _build_pod_spec(self):
        spec = {
            "containers": [
                {
                    "name": self.app.name,
                    "imageDetails": {"imagePath": "openfaas/gateway:0.20.2"},
                    "ports": [{"containerPort": 8080, "protocol": "TCP"}],
                    "files": [],
                    "config": {},  # used to store hashes of config file text
                    "env": [
                        {"functions_provider_url": "192.168.0.15:8081"},
                        {"direct_functions": "false"},
                        {"basic_auth": "false"},
                        {"faas_prometheus_host": "192.168.0.35"},
                        {"faas_prometheus_port": "9090"},
                    ]
                }
            ]
        }
```

Kubernetes schema:

```yaml
      containers:
      - name: gateway
        resources:
            requests:
              cpu: 50m
              memory: 120Mi
        image: openfaas/gateway:0.20.2
        imagePullPolicy: Always
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 10001
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          timeoutSeconds: 5
        env:
        - name: read_timeout
          value: "65s"
        - name: write_timeout
          value: "65s"
        - name: upstream_timeout
```
