### ISSUE TITLE
Operator charm messages not showing up in unit log on Juju 2.9.5

### ISSUE THREAD

**Issue by Vultaire** [canonical/operator#557]
I seem to have difficulty with Python logging log messages showing up in agent logs in Juju 2.9.5 with the operator framework.

I've created a fairly trivial charm based upon the "charmcraft init" autogenerated charm.  It's designed as a non-container charm, and simply exercises logging.

metadata.yaml has been reduced to:

```
name: test-charm
description: |
  TEMPLATE-TODO: fill out the charm's description
summary: |
  TEMPLATE-TODO: fill out the charm's summary
series:
- bionic
- focal
```

The guts of charm.py have been reduced to a minimum, and now looks like this:

```
#!/usr/bin/env python3

import logging
import sys

from ops.charm import CharmBase
from ops.framework import StoredState
from ops.main import main

logger = logging.getLogger(__name__)


class ErrorCharmCharm(CharmBase):
    """Charm the service."""

    _stored = StoredState()

    def __init__(self, *args):
        super().__init__(*args)
        self.framework.observe(self.on.config_changed, self._on_config_changed)

    def _on_config_changed(self, _):
        print('Stderr: The thing: {}'.format(repr(self.config["thing"])), file=sys.stderr)
        logger.error('Logger: The thing: {}'.format(repr(self.config["thing"])))


if __name__ == "__main__":
    main(ErrorCharmCharm)
```

What I expect to see: when I make a config change to the "thing" config option, I expect to see 2 log messages: one generated via the charm's stderr stream, and the other generated via the Python logging library.

What I see: stderr comes through, but the logging library does not.
