### ISSUE TITLE
Operator doesn't support running processes as `user` field for `pebble`

### ISSUE THREAD

**Issue by dasm** [canonical/operator#558]
I tried to build simple charm, based on [OpenSearch](https://hub.docker.com/r/opensearchproject/opensearch). It requires to run as non-root user.

Based on pebble layer change https://github.com/canonical/pebble/pull/35 user should be able to use `user` within layer definition:
```python
    def _on_pebble_ready(self, event: PebbleReadyEvent) -> None:                
        container = event.workload                                              
                                                                                
        cmd = "/usr/share/opensearch/bin/opensearch -Ecluster.name=name -Enode.name=node -Ediscovery.seed_hosts=seed -Ecluster.initial_master_nodes=master -Ediscovery.type=single-node"
                                                                                
        layer = {                                                               
            "summary": "opensearch layer",                                      
            "description": "pebble config layer for opensearchproject/opensearch",
            "services": {                                                       
                "opensearch": {                                                 
                    "user": "opensearch",                                       
                    "override": "merge",                                        
                    "environment": {"OPENSEARCH_JAVA_OPTS": f"-Xms512M -Xmx512M"},
                    "summary": "opensearch",                                    
                    "command": cmd,                                             
                    "startup": "enabled",                                       
                }                                                               
            }                                                                   
        }                                                                       
                                                                                
        container.add_layer("opensearch", layer, combine=True)                  
        container.autostart()                                                   
        self.unit.status = ActiveStatus()                                       
```

However when I ran it I got
```
2021-06-28T21:06:08.105Z [opensearch] java.lang.RuntimeException: can not run opensearch as root
```

I checked pebble plan and it showed me this:
```
dasm@dell:~/git/charm-opensearch-k8s$ k exec -it pod/opensearch-k8s-0 -c opensearch -n development -- /charm/bin/pebble plan
services:
    opensearch:
        summary: opensearch
        startup: enabled
        override: merge
        command: /usr/share/opensearch/bin/opensearch -Ecluster.name=name -Enode.name=node -Ediscovery.seed_hosts=seed -Ecluster.initial_master_nodes=master -Ediscovery.type=single-node
        environment:
            OPENSEARCH_JAVA_OPTS: -Xms512M -Xmx512M
```

`opensearch` user exists in the `/etc/passwd` file

```
bash-4.2# cat /etc/passwd | grep opensearch
opensearch:x:1000:1000::/usr/share/opensearch:/bin/bash
```
