### ISSUE TITLE
Simplify gathering of peer address

### ISSUE THREAD

**Issue by balbirthomas** [canonical/operator#560]
# Introduction

In developing Observability charms it has been noted that a common use case is to gather the current list of IP address of the peers in a charm. For example if a charm would like all of its units to be scrape targets for Prometheus then it needs to provide this provide this list of IP address (of all its units), and these addresses need to be accessible from Prometheus (which may be cross model). There have been similar use cases with other charms for example the relation between Alertmanager and Prometheus and so on. Each charm with such a use case has to implement mechanisms to gather and maintain this list of IP address through the charm's lifecycle. Such duplication of effort can be minimised and the development of charms simplified if the Operator Framework provides a simple way to introspect and obtain such a list of IP address. For example if `CharmBase` can expose a property such as `self.app.units` or `self.charm.units` that is a nested data structure of all units and their metadata such as public and private IP address. 

Providing such an interface to gather list of peer IPs will also simplify creation of consumer charm libraries (i.e. objects derived from `ops.relation.ConsumerBase`). This is because it is often the task of the consumer to forward the list of IPs to the provider (`ops.relation.ProviderBase`) . However the it may be odd for the consumer charm library to be accessing peer relations of the Consumer charm directly. This is because the consumer charm library is created by the Provider charm. `ConsumerBase` does have a handle to the Consumer charm. Hence if peer metadata is exposed through the `CharmBase` object then the consumer library may easily access it.

**Comment by benhoyt** [comment]
@sed-i or @PietroPasotti, do either of you have a good handle on this issue, particularly as it relates to the Observability charms? Tony and I were thinking of discussing it at the eng sprint?

**Comment by sed-i** [comment]
This was originally needed for forming a gossip ring between alertmanager units (peers).

In k8s we no longer use IP addresses, only fqdn.
But @weiiwang01 plans to use IP addresses for nginx. Perhaps he'd be able to spec this further.

More context:

`juju show-unit` prints out two kinds of IP addresses:
1. App IP in relation data that is auto populated by juju and is accessible to charm code.
2. Unit IP that is not in relation data and is only available via ops bind_address (which sometimes returns None).

```yaml
    related-units:
      ca/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.105/32
          ingress-address: 10.152.183.105
          private-address: 10.152.183.105  # <-- App IP in relation data (auto generated by juju)
  provider-id: mc-1
  address: 10.1.166.94  # <-- Unit IP (must use bind_address to obtain in charm code)
```

Related:
- #534
- #538 
- #972
