### ISSUE TITLE
ingest mounted location into CharmMeta

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#579]
Obtaining storage location via the storages section,
```python
self.meta.storages["data"].location
```
is not very useful for k8s charms because for k8s charms that sepcifies mount point in the charm container, not the workload.
For the workload, would need something like:
```python
self.meta.containers[self._container_name].mounts[0].location
```
or
```python
self.meta.containers[self._container_name].mounts.data.location
```

However, mounted location is not ingested by CharmMeta
https://github.com/canonical/operator/blob/b1a8fffc053fbbdaf43b826e78c220bfdae4c8fe/ops/charm.py#L891-L892

**Comment by rbarry82** [comment]
Can you give an example of the charm metadata YAML? Charm Metadata V2 (not yet fully supported by OF) allows [specifying mounts under containers](https://discourse.charmhub.io/t/charm-metadata-v2/3674/15?u=rbarry). This is likely to be the only way in which this is supported by OF, instead of trying to iterate through the running containers to create this "in reverse".

Does that work?

**Comment by sed-i** [comment]
The relevant section of metadata.yaml:
```yaml
        name: DummyConsumerCharm
        storage:
          data:
            type: filesystem
            location: /this/is/charm
        containers:
          consumer-charm:
            resource: consumer-charm-image
            mounts:
              - storage: data
                location: /this/is/workload
```
I would like to be able to
```python
# works
"/this/is/charm" == self.harness.charm.meta.storages["data"].location

# not yet implemented
"/this/is/workload" == self.harness.charm.meta.containers["alertmanager"].mounts["data"].location
```
But can't because:
https://github.com/canonical/operator/blob/3d0c36479109214dbe737f4ce8388e870a09e34b/ops/charm.py#L734-L738

which is exactly what this issue is about :)
