### ISSUE TITLE
obtain storage path in charm container by storage name

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#646]
I would like to be able to obtain the mounted storage location in a *charm* container, by storage name.

For [example](https://juju.is/docs/sdk/storage):
```yaml
storage:
  logs:
    type: filesystem
    # specifying location on the charm container is optional
    # when unspecified, defaults to /var/lib/juju/storage/<name>/<num>
```
From charm code, I would like to be able to do something like "get_storage_path("logs")".

One option is to increase the scope of `self.meta` from `metadata.yaml` to a broader definition.
(`self.meta.storages["logs"].location` in this case would be `None`.)

**Comment by jnsgruk** [comment]
Have just been re-reading the surrounding chat on this issue... taking the example:

```yaml
containers:
  loki:
    resource: loki-image
    mounts:
      - storage: active-index-directory
        location: /loki/boltdb-shipper-active
      - storage: loki-chunks
        location: /loki/chunks

storage:
  active-index-directory:
    type: filesystem
    description: Mount point in which Loki will store index
  loki-chunks:
    type: filesystem
    description: Mount point in which Loki will store chunks (objects)
```

In this case, `self.meta.storages["logs"].location` would return `None`, whereas `self.meta.containers["loki-container"].mounts["active-index-directory"].location` would (correctly) return `/loki/boltdb-shipper-active`?
