### ISSUE TITLE
means to test charm's interaction with the charm container filesystem

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#681]
I have a sidecar with mounted storage that my charm needs to read and update relation data with:

```yaml
containers:
  git-sync:
    resource: git-sync-image
    mounts:
      - storage: content-from-git
        location: /git

storage:
  content-from-git:
    type: filesystem
    description: >
      Where to store the checked-out content from the git repo.
    location: /git
```

The charm reads content from the `/git` folder in the charm container and all is good.

For unit testing, I was hoping I could
`self.harness.model.unit.get_container("charm").push(...)`

but that gives
`ops.model.ModelError: container 'charm' not found`

because
https://github.com/canonical/operator/blob/28d9870b5b76be12c949c7b49964dcc26969f68f/ops/model.py#L302

and `meta.containers` obviously does not include "charm".

One solution that works is passing to Harness a metadata that has its `"location"` value replaced by `tempfile.mkdtemp()` etc. so the test code is interacting with the test runner's `/tmp` filesystem

https://github.com/sed-i/lma-rules-operator/blob/9b318d2a3144ddf0269dab1c57e521d7cb6daa7c/tests/unit/prometheus-config/test_app_relation_data.py#L55

but I was wondering if this use case makes sense for Harness to support internally.
