### ISSUE TITLE
`harness.get_relation_data()` returns `{}` although charm under test has set relation data

### ISSUE THREAD

**Issue by AurelienLourot** [canonical/operator#703]
Although the machine charm under test sets relation data to the other charm in the `relation-joined` hook, `harness,get_relation_data()` still returns `{}`, making it impossible to write corresponding test expectations.

This is hitting us while pulling the ops framework from source (`master`) on 2022-02-17.

```
# metadata.yaml
name: nova-compute-nvidia-vgpu
subordinate: true
provides:
  nova-vgpu:
    interface: nova-vgpu
    scope: container
requires:
  juju-info:
    interface: juju-info
    scope: container
```

```
# src/charm.py

class NovaComputeNvidiaVgpuCharm(CharmBase):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.framework.observe(self.on.nova_vgpu_relation_joined,
                               self._on_nova_vgpu_relation_joined_or_changed)
        self.framework.observe(self.on.nova_vgpu_relation_changed,
                               self._on_nova_vgpu_relation_joined_or_changed)

    def _on_nova_vgpu_relation_joined_or_changed(self, event):
        print('I HAVE BEEN CALLED')
        event.relation.data[self.unit]['hello'] = 'hi'
```

```
# unit_tests/test_charm.py

class TestNovaComputeNvidiaVgpuCharm(CharmTestCase):

    def setUp(self):
        self.harness = Harness(src.charm.NovaComputeNvidiaVgpuCharm)
        self.addCleanup(self.harness.cleanup)
        self.harness.begin()

    def test_nova_vgpu_relation_joined(self):
        self.harness.set_leader(True)
        relation_id = self.harness.add_relation('nova-vgpu', 'nova-compute')
        self.harness.add_relation_unit(relation_id, 'nova-compute/0')

        # PROBLEM: at this point this returns {} instead of {'hello': 'hi'}
        # although we know that _on_nova_vgpu_relation_joined_or_changed() has
        # been called:
        self.harness.get_relation_data(relation_id, 'nova-compute/0')
```
