### ISSUE TITLE
Error when trying to pack k8s charm on ubuntu 20.04

### ISSUE THREAD

**Issue by arturo-seijas** [canonical/operator#851]
Hi!

I've just come across [this error](https://pastebin.canonical.com/p/JWgFnJZWVP/) when trying to pack a k8s charm with the  charmcraft.yaml below. However, when packing with ubuntu 22.04 it works properly.
This seems to be caused by the new version 65.5.1 of setuptools that `ops`is pulling https://pypi.org/project/setuptools/#history so I'm reporting it here.
```
type: "charm"
bases:
  - build-on:
    - name: "ubuntu"
      channel: "20.04"
    run-on:
    - name: "ubuntu"
      channel: "20.04"
 ```

Thank you!
