### ISSUE TITLE
`get_binding` returns the same thing for different relations

### ISSUE THREAD

**Issue by sed-i** [canonical/operator#972]
## Problem
`get_binding(event.relation)` returns the same addresses for different relations, while `juju show-unit` shows, as expected, different addresses for different relations.

## Reproduction
After adding the following to `alertmanager_dispatch` "relation joined":
```diff
diff --git a/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py b/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
index 3513234..f16feeb 100644
--- a/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
+++ b/lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
@@ -297,6 +297,18 @@ class AlertmanagerProvider(RelationManagerBase):
         This is needed for consumers such as prometheus, which should be aware of all alertmanager
         instances.
         """
+        try:
+            bind = self.charm.model.get_binding(event.relation)
+            logger.info(
+                "Binding %s: [bind_address=%s, ingress_address=%s, ingress_addresses=%s]",
+                bind.name,
+                bind.network.bind_address,
+                bind.network.ingress_address,
+                bind.network.ingress_addresses,
+            )
+        except Exception as e:
+            logger.error("Failed to get_binding(): %s", e)
+
         self.update_relation_data(event)
```

And relating two apps: "prom" in the same model and "remote-prom" from a different model.
As a result, I see this:
```
juju debug-log --tail | grep "bind"
unit-am-0: 09:38:01.993 INFO unit.am/0.juju-log alerting:16: Binding alerting: [bind_address=10.1.166.91, ingress_address=10.152.183.65, ingress_addresses=[IPv4Address('10.152.183.65')]]
unit-am-0: 09:38:53.542 INFO unit.am/0.juju-log alerting:17: Binding alerting: [bind_address=10.1.166.91, ingress_address=10.152.183.65, ingress_addresses=[IPv4Address('10.152.183.65')]]
```

Looking at `juju show-unit`, I can see that:
1. For some reason, all the addresses (egress-subnets, ingress-address, private-address) are identical (per unit). Why ingress address is the same as private address?
2. There are no hostnames listed for the CMR.
3. ops gives the same addresses for both relations.

```yaml
  - relation-id: 16
    endpoint: alerting
    related-endpoint: alertmanager
    application-data: {}
    related-units:
      prom/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.83/32
          ingress-address: 10.152.183.83
          private-address: 10.152.183.83
  - relation-id: 17
    endpoint: alerting
    cross-model: true
    related-endpoint: alertmanager
    application-data: {}
    related-units:
      remote-f8775ab80e3d4c9d8ab7b4030b7cdee7/0:
        in-scope: true
        data:
          egress-subnets: 10.152.183.221/32
          ingress-address: 10.152.183.221
          private-address: 10.152.183.221
  provider-id: am-0
```

## Related issues
- https://github.com/canonical/operator/issues/534
